/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inner;

public class App {

    private String reduntantVar = "simpleVar";   

    public String getGreeting() {
        return "Hello world from inner.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
